actors:
  shoya140:
    image_url: /images/actors/shoya140.png
    name: shoya140
    url: https://shoya.io
  101kaz:
    image_url: /images/actors/101kaz.jpg
    name: 101kaz
    url: https://kazy.hatenablog.com
  tak0303:
    image_url: /images/actors/tak0303.jpg
    name: tak0303
    url: https://takashi.im
  bussorenre:
    image_url: /images/actors/bussorenre.jpg
    name: bussorenre
    url: http://bussorenre.hatenablog.jp/
  becolomochi:
    image_url: /images/actors/becolomochi.jpg
    name: becolomochi
    url: http://develop.becolomochi.com
  pika_shi:
    image_url: /images/actors/pika_shi.jpg
    name: pika_shi
    url: https://pikashi.tokyo
  yumiyon:
    image_url: /images/actors/yumiyon.png
    name: yumiyon
    url: http://piyon.hatenablog.com
author: Shoya Ishimaru
description: 様々な分野の猛者をゲストに迎えてソフトウェア開発の話題を中心にゆるく話すポッドキャスト番組
description_long: 様々な分野の猛者をゲストに迎えてソフトウェア開発の話題を中心にゆるく話すポッドキャスト番組
email: mosahq@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics: UA-89650641-3
hashtag: mosafm
itunes_podcast_url: https://itunes.apple.com/jp/podcast/mosa-fm/id1384305911?mt=2
keywords: podcast, software engineering, productivity
language: ja
markdown: kramdown
permalink: /:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: mosa.fm
url: https://mosa.fm
