actors:
  shoya140:
    image_url: /images/actors/shoya140.png
    name: shoya140
    url: https://shoya.io
  101kaz:
    image_url: /images/actors/101kaz.jpg
    name: 101kaz
    url: https://kazy.hatenablog.com/
author: Shoya Ishimaru
description: 様々な分野の猛者をゲストに迎えてソフトウェア開発の話題を中心にゆるく話すポッドキャスト番組
description_long: 様々な分野の猛者をゲストに迎えてソフトウェア開発の話題を中心にゆるく話すポッドキャスト番組
email: mosahq@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: mosafm
itunes_podcast_url:
keywords: podcast, software engineering, productivity
language: ja
markdown: kramdown
permalink: /:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: mosa.fm
url: https://mosa.fm
