actors:
  alice:
    image_url: /images/actors/alice.png
    name: alice
    url: https://sns.example.com/alice
  bob:
    image_url: /images/actors/bob.png
    name: bob
    url: https://sns.example.com/bob
author: alice
description: Coming soon...
description_long: 界隈の猛者がソフトウェア開発の話題を中心にゆるく話すポッドキャスト番組
email: info@example.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: mosafm
itunes_podcast_url:
keywords: comma,separated,keywords
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: mosa.fm
url: https://mosa.fm
